In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display

print("Libraries imported successfully!")

Libraries imported successfully!

In [6]:
import pandas as pd
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

print("First 5 records:")
display(df.head())

print("\nDataset information:")
df.info()

print("\nMissing values in each column:")
display(df.isnull().sum().to_frame("Missing_Count"))

print("\nNumber of completely duplicated rows:")
print(df.duplicated().sum())

print("\nOriginal dataset dimensions:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

First 5 records:

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

Missing values in each column:

                    Missing_Count
longitude                       0
latitude                        0
housing_median_age              0
total_rooms                     0
total_bedrooms                  0
population                      0
households                      0
median_income                   0
median_house_value              0

Number of completely duplicated rows:
0

Original dataset dimensions:
Rows: 17000
Columns: 9

In [7]:
df_clean = df.copy()

duplicates_before = df_clean.duplicated().sum()

df_clean = df_clean.drop_duplicates()

duplicates_after = df_clean.duplicated().sum()

print("Duplicate rows before cleaning:", duplicates_before)
print("Duplicate rows after cleaning:", duplicates_after)
print("Shape after duplicate removal:", df_clean.shape)

display(df_clean)

Duplicate rows before cleaning: 0
Duplicate rows after cleaning: 0
Shape after duplicate removal: (17000, 9)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [12]:
numeric_columns = df_clean.select_dtypes(include=['number']).columns.tolist()
categorical_columns = df_clean.select_dtypes(exclude=['number']).columns.tolist()

# Fill missing numerical values with the median
for column in numeric_columns:
    if column in df_clean.columns:
        df_clean[column] = df_clean[column].fillna(df_clean[column].median())

# Fill missing categorical values with the mode
for column in categorical_columns:
    if column in df_clean.columns:
        mode_values = df_clean[column].mode(dropna=True)
        if not mode_values.empty:
            df_clean[column] = df_clean[column].fillna(mode_values.iloc[0])
        else:
            df_clean[column] = df_clean[column].fillna("Unknown")

print("Missing values handled successfully!")
print("\nMissing values after imputation:")
display(df_clean.isnull().sum().to_frame("Missing_Count"))

Missing values handled successfully!

Missing values after imputation:

                    Missing_Count
longitude                       0
latitude                        0
housing_median_age              0
total_rooms                     0
total_bedrooms                  0
population                      0
households                      0
median_income                   0
median_house_value              0

In [3]:
import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display

print("Libraries imported successfully!")
import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display

print("Libraries imported successfully!")

Libraries imported successfully!
Libraries imported successfully!

In [13]:
text_columns = df_clean.select_dtypes(
    include=["object", "string"]
).columns

for column in text_columns:
    df_clean[column] = (
        df_clean[column]
        .astype("string")
        .str.strip()
        .str.lower()
    )

print("Text standardization completed!")

display(df_clean)

Text standardization completed!

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [14]:
print("========== DATA QUALITY REPORT ==========")

print("\nOriginal shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

print("\nRemaining duplicate rows:")
print(df_clean.duplicated().sum())

print("\nTotal missing values:")
print(df_clean.isnull().sum().sum())

print("\nMissing values by column:")
display(df_clean.isnull().sum().to_frame("Missing_Count"))

print("\nData types after cleaning:")
display(df_clean.dtypes.to_frame("Data_Type"))

print("\nValidation completed!")

========== DATA QUALITY REPORT ==========

Original shape: (17000, 9)
Cleaned shape: (17000, 9)

Remaining duplicate rows:
0

Total missing values:
0

Missing values by column:

                    Missing_Count
longitude                       0
latitude                        0
housing_median_age              0
total_rooms                     0
total_bedrooms                  0
population                      0
households                      0
median_income                   0
median_house_value              0

Data types after cleaning:

                   Data_Type
longitude            float64
latitude             float64
housing_median_age   float64
total_rooms          float64
total_bedrooms       float64
population           float64
households           float64
median_income        float64
median_house_value   float64

Validation completed!

In [17]:
print("Numerical summary statistics:")
numerical_summary = df_clean.describe()
display(numerical_summary)

# Save numerical report
numerical_summary.to_csv("numerical_summary.csv")

# Check if there are any object (categorical) columns before describing them
categorical_cols = df_clean.select_dtypes(include=["object"]).columns
if len(categorical_cols) > 0:
    print("\nCategorical summary statistics:")
    categorical_summary = df_clean.describe(include="object")
    display(categorical_summary)
    categorical_summary.to_csv("categorical_summary.csv")
else:
    print("\nNo categorical columns found. Skipping categorical summary.")

print("\nSummary statistics saved successfully!")

Numerical summary statistics:

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

No categorical columns found. Skipping categorical summary.

Summary statistics saved successfully!

In [18]:
# Cell 9: Export cleaned dataset

df_clean.to_csv("cleaned_sales.csv", index=False)

print("Cleaned dataset saved as cleaned_sales.csv")
print("Raw dataset saved as raw_sales.csv")

print("\nCleaned dataset preview:")
display(df_clean.head())

print("\nFinal dataset shape:", df_clean.shape)

Cleaned dataset saved as cleaned_sales.csv
Raw dataset saved as raw_sales.csv

Cleaned dataset preview:

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

Final dataset shape: (17000, 9)

In [20]:
import os
from google.colab import files

output_files = [
    "raw_sales.csv",
    "cleaned_sales.csv",
    "numerical_summary.csv",
    "categorical_summary.csv"
]

for filename in output_files:
    if os.path.exists(filename):
        files.download(filename)
    else:
        print(f"Skipping {filename} as it does not exist.")

Skipping raw_sales.csv as it does not exist.

Skipping categorical_summary.csv as it does not exist.

In [21]:

# Cell 11: Create README documentation

readme_content = f"""# Corporate Sales Record Cleaner
## Automated Data Sanitization Pipeline

### Project Overview
This project cleans a raw sales dataset using Python and Pandas.

### Technologies Used
- Python
- Pandas
- NumPy
- Google Colab


### Before and After Dimensions
- Original dataset shape: {df.shape}
- Cleaned dataset shape: {df_clean.shape}

### Data Quality Results
- Duplicate rows in original dataset: {df.duplicated().sum()}
- Duplicate rows after cleaning: {df_clean.duplicated().sum()}
- Missing values after cleaning: {df_clean.isnull().sum().sum()}

### Project Files
- raw_sales.csv: Original uncleaned dataset.
- cleaned_sales.csv: Sanitized dataset.
- numerical_summary.csv: Numerical descriptive statistics.
- categorical_summary.csv: Categorical descriptive statistics.
- sales_record_cleaner.ipynb: Google Colab notebook.

### How to Run
Open the notebook in Google Colab and run each cell from top to bottom.
"""

with open("README.md", "w", encoding="utf-8") as file:
    file.write(readme_content)

print("README.md created successfully!")

# Download README
files.download("README.md")

README.md created successfully!